services:

  app:
    build: .
    container_name: cysuites
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      - ./storage:/var/www/html/storage
      - ./bootstrap/cache:/var/www/html/bootstrap/cache
    ports:
      - "5173:5173"
    depends_on:
      - db

  nginx:
    image: nginx:stable-alpine
    container_name: cysuites_nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: db
    environment:
      MYSQL_DATABASE: cysuites
      MYSQL_ROOT_PASSWORD: laravel0577
      MYSQL_USER: donald
      MYSQL_PASSWORD: laravel0577
    ports:
      - "3307:3306"
